sudo: false
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu
    packages:
      - libcunit1-dev
      - libcunit1
      - texinfo
script: autoreconf -i && ./configure && make && make check
